adding YML templates to localgov repo
localgovdrupal/localgov pull request #462
Opened 2022-07-13 10:15 UTC by LauraHilliger

created two YML templates

2022-07-13 11:41 UTC, msayoung requested changes

2022-07-13 11:41 UTC, msayoung commented on README.md
> +# Welcome! 👋👋🏿👋🏽👋🏻👋🏾👋🏼
Did you mean to change this file?
It seems to be a repetition of Readme on https://github.com/localgovdrupal

2022-07-13 11:47 UTC, LauraHilliger commented on README.md
> +# Welcome! 👋👋🏿👋🏽👋🏻👋🏾👋🏼
ah, @dajbelshaw sent a separate PR 12 days ago with just that commit. We merged it just an hour ago with @aaronhirtenstein – actually we only wanted to merge the YML templates...I think @aaronhirtenstein was going to chat with you about this

2022-07-18 13:31 UTC, finnlewis commented
Just discussing in Merge Monday, @msayoung thinks this needs more work.

2022-07-19 08:09 UTC, LauraHilliger commented
@msayoung - I believe we can just close this?

2022-07-19 15:34 UTC, closed without merging

2022-07-19 15:34 UTC, finnlewis commented
Thanks @LauraHilliger  - closing this in favour of https://github.com/localgovdrupal/localgov/pull/464