Added views block for revision log
localgovdrupal/localgov pull request #715
Opened 2024-05-21 16:13 UTC by anthonylindsay

uses core views to create a view of node revision log entries and dates, rendered as a block.
Uses a contextual filter to filter to a node ID.
Designed for display on a node.

2024-05-22 10:43 UTC, markconroy requested changes
This looks very handy.

I think it might be worth doing 2 more things

1. Use "HTML List" as the formatting option instead of "Unformatted list", and
2. Link the revision date to the revisions tab for that node.

Here's a screenshot of what I mean (I can't add it to this PR since it's outside of the LGD group).

![Screenshot 2024-05-22 at 11 42 03](https://github.com/localgovdrupal/localgov/assets/2183332/4bc3280b-6e3c-4748-82c8-b529edf64cc8)

===

Thanks to [Big Blue Door](https://www.bigbluedoor.net/) for sponsoring my time to work on this.

2024-05-22 10:43 UTC, markconroy commented on config/install/views.view.revision_log.yml
> +uuid: f20313f2-0a70-4df0-ba43-ba517491abb5
Can we remove the UUID from this please

2024-05-28 11:31 UTC, finnlewis commented
Discussed at Merge Tuesday, we'll hang tight for the changes requested.

2024-06-26 16:06 UTC, markconroy commented
I've created a PR for this with the requested changes and some other updates as well. It's here: https://github.com/localgovdrupal/localgov/pull/735

I think we can close this one now.

2025-04-15 11:15 UTC, finnlewis commented
I think we're closing this in favour of https://github.com/localgovdrupal/localgov/pull/735

2025-04-15 11:15 UTC, closed without merging